Network fixes

diff --git a/loadjb-config b/loadjb-config
--- a/loadjb-config
+++ b/loadjb-config
@@ -1,7 +1,7 @@
 #!/bin/bash
 ####################
 ### loadconfig #####
-version=0.8 ########
+version=0.9 ########
 ### JustBrowsing ###
 ####################
 
@@ -11,10 +11,11 @@ saveDir="/etc/justbrowsing/data"
 configFile="${saveDir}/config"
 cfgFile="${mntDir}/justbrowsing.cfg"
 netFile="${mntDir}/networking"
+logFile="/tmp/loadcfg.log"
 
-EXIT_STATUS() { echo "ERROR: $@"; exit 1; }
+EXIT_STATUS() { echo "ERROR: $@" | tee -a "$logFile"; exit 1; }
 
-PARSE_BOOT() { 
+PARSE_BOOT() {
   cat /proc/cmdline 2>/dev/null | grep -o "$1=\S*" | awk -F = '{print $2}' | tail -n 1; 
 }
 
@@ -35,7 +36,7 @@ OVERRIDE_CONFIG() {
 
 UNPACK_DATA() {
   cypher="enc -aes-256-cbc -salt"
-  index=$(hexdump "/usr/share/pixmaps/jbconfig.png")
+  index="/usr/share/pixmaps/jbconfig.png"
   openssl $cypher -in "$netFile" -d -pass "file:$index" | tar -C "$saveDir" -xzv
 }
 
@@ -48,7 +49,7 @@ if [ -b "$probeDevice" -a "$skipcfg" != "true" ]; then
   mkdir -p "$mntDir" "$saveDir" || EXIT_STATUS "unable to create dirs: $mntDir $saveDir"
   mount -o ro "$probeDevice" "$mntDir" || EXIT_STATUS "unable to mount $probeDevice"
   [ -f "$cfgFile" ] && cp "$cfgFile" "$configFile"
-  [ -f "$netFile" ] && UNPACK_DATA
+  [ -f "$netFile" ] && UNPACK_DATA | tee -a "$logFile"
   umount "$mntDir" 2>/dev/null || EXIT_STATUS "unable to unmount $mntDir"
 fi
 
